<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clean up existing products to avoid duplicates
        Product::query()->delete();
        ProductImage::query()->delete();

        $products = [
            [
                'name' => 'Rumah Mewah Bintaro',
                'type' => 'house',
                'description' => 'Rumah mewah 2 lantai dengan desain modern minimalis di kawasan Bintaro yang strategis. Dilengkapi dengan taman luas dan carport untuk 2 mobil.',
                'price' => 2500000000,
                'land_area' => 200,
                'building_area' => 180,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'floors' => 2,
                'garage' => 2,
                'location' => 'Jl. Bintaro Utama Sektor 9',
                'city' => 'Tangerang Selatan',
                'province' => 'Banten',
                'latitude' => -6.2745,
                'longitude' => 106.7546,
                'facilities' => ['Swimming Pool', 'Garden', 'Security 24/7', 'CCTV', 'Smart Home'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Apartemen Green Bay Pluit',
                'type' => 'apartment',
                'description' => 'Apartemen studio fully furnished di Green Bay Pluit dengan view laut yang menakjubkan. Lokasi strategis dekat dengan mall dan transportasi umum.',
                'price' => 850000000,
                'building_area' => 35,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'floors' => 1,
                'garage' => 1,
                'location' => 'Green Bay Pluit Tower Manhattan',
                'city' => 'Jakarta Utara',
                'province' => 'DKI Jakarta',
                'latitude' => -6.1184,
                'longitude' => 106.7875,
                'facilities' => ['Swimming Pool', 'Gym', 'Jogging Track', 'Mall Access', 'Sea View'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Villa Modern Puncak',
                'type' => 'house',
                'description' => 'Villa eksklusif dengan pemandangan pegunungan yang memukau. Cocok untuk investasi atau hunian pribadi.',
                'price' => 4500000000,
                'land_area' => 500,
                'building_area' => 300,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'floors' => 2,
                'garage' => 3,
                'location' => 'Jl. Raya Puncak KM 87',
                'city' => 'Bogor',
                'province' => 'Jawa Barat',
                'latitude' => -6.7016,
                'longitude' => 106.9510,
                'facilities' => ['Private Pool', 'Garden', 'Mountain View', 'BBQ Area', 'Gazebo'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Ruko 3 Lantai BSD City',
                'type' => 'house',
                'description' => 'Ruko strategis di jalur utama BSD City. Cocok untuk berbagai jenis usaha dengan traffic tinggi.',
                'price' => 3200000000,
                'land_area' => 80,
                'building_area' => 200,
                'bedrooms' => 0,
                'bathrooms' => 3,
                'floors' => 3,
                'garage' => 2,
                'location' => 'Jl. BSD Raya Utama Sektor 14',
                'city' => 'Tangerang Selatan',
                'province' => 'Banten',
                'latitude' => -6.3023,
                'longitude' => 106.6392,
                'facilities' => ['High Traffic', 'Parking Area', 'Wide Frontage', 'Near Mall', 'CCTV'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Townhouse Pondok Indah',
                'type' => 'house',
                'description' => 'Townhouse modern minimalis di kawasan elite Pondok Indah. Desain kontemporer dengan fasilitas lengkap.',
                'price' => 5800000000,
                'land_area' => 150,
                'building_area' => 220,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'floors' => 3,
                'garage' => 2,
                'location' => 'Jl. Metro Pondok Indah',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'latitude' => -6.2648,
                'longitude' => 106.7843,
                'facilities' => ['Private Pool', 'Rooftop', 'Smart Home', 'Security', 'Club House'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Rumah Cluster Grand Wisata',
                'type' => 'house',
                'description' => 'Rumah cluster dengan konsep one gate system. Lingkungan aman dan nyaman untuk keluarga.',
                'price' => 1200000000,
                'land_area' => 120,
                'building_area' => 90,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'floors' => 2,
                'garage' => 1,
                'location' => 'Grand Wisata Blok AA No. 15',
                'city' => 'Bekasi',
                'province' => 'Jawa Barat',
                'latitude' => -6.2763,
                'longitude' => 107.0036,
                'facilities' => ['Jogging Track', 'Playground', 'Security 24/7', 'Club House', 'Swimming Pool'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Apartemen Bintaro Plaza',
                'type' => 'apartment',
                'description' => 'Apartemen 2 bedroom strategis di atas mall Bintaro Plaza. Akses mudah ke berbagai fasilitas.',
                'price' => 1350000000,
                'building_area' => 48,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'floors' => 1,
                'garage' => 1,
                'location' => 'Bintaro Plaza Residence Tower A',
                'city' => 'Tangerang Selatan',
                'province' => 'Banten',
                'latitude' => -6.2689,
                'longitude' => 106.7519,
                'facilities' => ['Mall Access', 'Swimming Pool', 'Gym', 'Sky Garden', 'Parking'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Rumah Subsidi Cibubur',
                'type' => 'house',
                'description' => 'Rumah subsidi dengan desain modern. Cocok untuk keluarga muda yang ingin memiliki rumah pertama.',
                'price' => 350000000,
                'land_area' => 72,
                'building_area' => 36,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'floors' => 1,
                'garage' => 0,
                'location' => 'Perumahan Griya Asri Cibubur',
                'city' => 'Depok',
                'province' => 'Jawa Barat',
                'latitude' => -6.3732,
                'longitude' => 106.8989,
                'facilities' => ['Playground', 'Masjid', 'Security', 'Water Supply', 'Electricity'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Penthouse Menteng Park',
                'type' => 'apartment',
                'description' => 'Penthouse mewah dengan rooftop private pool. View 360 derajat kota Jakarta yang spektakuler.',
                'price' => 12000000000,
                'building_area' => 250,
                'bedrooms' => 4,
                'bathrooms' => 4,
                'floors' => 2,
                'garage' => 3,
                'location' => 'Menteng Park Tower Diamond',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'latitude' => -6.1944,
                'longitude' => 106.8294,
                'facilities' => ['Private Pool', 'Rooftop', 'Elevator', 'City View', 'Smart Home'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Kavling Siap Bangun Sentul',
                'type' => 'land',
                'description' => 'Kavling tanah siap bangun di kawasan Sentul City. Investasi jangka panjang yang menguntungkan.',
                'price' => 800000000,
                'land_area' => 400,
                'building_area' => 0,
                'bedrooms' => 0,
                'bathrooms' => 0,
                'floors' => 0,
                'garage' => 0,
                'location' => 'Sentul City Blok D',
                'city' => 'Bogor',
                'province' => 'Jawa Barat',
                'latitude' => -6.5633,
                'longitude' => 106.9276,
                'facilities' => ['Clean Certificate', 'Road Access', 'Electricity', 'Water Source', 'Security'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Rumah Second Cipete',
                'type' => 'house',
                'description' => 'Rumah second dalam kondisi terawat di kawasan Cipete yang tenang dan asri.',
                'price' => 3500000000,
                'land_area' => 180,
                'building_area' => 150,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'floors' => 2,
                'garage' => 2,
                'location' => 'Jl. Cipete Raya No. 45',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'latitude' => -6.2745,
                'longitude' => 106.8003,
                'facilities' => ['Garden', 'Carport', 'Kitchen Set', 'Water Heater', 'AC'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Kondominium Ancol',
                'type' => 'apartment',
                'description' => 'Kondominium dengan akses langsung ke pantai Ancol. Fasilitas resort lengkap.',
                'price' => 2800000000,
                'building_area' => 85,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'floors' => 1,
                'garage' => 1,
                'location' => 'Ancol Beach City Mediterania',
                'city' => 'Jakarta Utara',
                'province' => 'DKI Jakarta',
                'latitude' => -6.1226,
                'longitude' => 106.8426,
                'facilities' => ['Beach Access', 'Swimming Pool', 'Gym', 'Restaurant', 'Security'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Rumah Syariah Bogor',
                'type' => 'house',
                'description' => 'Rumah dengan skema pembiayaan syariah tanpa riba. Proses mudah dan cepat.',
                'price' => 950000000,
                'land_area' => 100,
                'building_area' => 75,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'floors' => 1,
                'garage' => 1,
                'location' => 'Perumahan Islami Bogor Asri',
                'city' => 'Bogor',
                'province' => 'Jawa Barat',
                'latitude' => -6.5978,
                'longitude' => 106.8064,
                'facilities' => ['Masjid', 'Islamic School', 'Security', 'Park', 'Syariah Compliant'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Warehouse Cakung',
                'type' => 'house',
                'description' => 'Gudang strategis dekat tol dengan akses mudah untuk logistik. Cocok untuk distribusi.',
                'price' => 5500000000,
                'land_area' => 1000,
                'building_area' => 800,
                'bedrooms' => 0,
                'bathrooms' => 2,
                'floors' => 1,
                'garage' => 5,
                'location' => 'Kawasan Industri Cakung',
                'city' => 'Jakarta Timur',
                'province' => 'DKI Jakarta',
                'latitude' => -6.1677,
                'longitude' => 106.9503,
                'facilities' => ['Loading Dock', 'High Ceiling', 'Security', 'Parking', 'Near Highway'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Rumah Smart Home Gading Serpong',
                'type' => 'house',
                'description' => 'Rumah dengan teknologi smart home lengkap. Kontrol semua dari smartphone.',
                'price' => 3800000000,
                'land_area' => 200,
                'building_area' => 175,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'floors' => 2,
                'garage' => 2,
                'location' => 'Summarecon Gading Serpong',
                'city' => 'Tangerang',
                'province' => 'Banten',
                'latitude' => -6.2429,
                'longitude' => 106.6220,
                'facilities' => ['Smart Home', 'Solar Panel', 'CCTV', 'Automated Gate', 'Pool'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Rumah Dekat MRT Lebak Bulus',
                'type' => 'house',
                'description' => 'Rumah strategis hanya 5 menit jalan kaki ke stasiun MRT Lebak Bulus.',
                'price' => 2800000000,
                'land_area' => 140,
                'building_area' => 120,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'floors' => 2,
                'garage' => 1,
                'location' => 'Jl. Lebak Bulus Raya',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'latitude' => -6.2894,
                'longitude' => 106.7749,
                'facilities' => ['Near MRT', 'Mall Access', 'Security', 'Garden', 'Carport'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Villa Pantai Anyer',
                'type' => 'house',
                'description' => 'Villa tepi pantai dengan private beach access. Perfect untuk weekend getaway.',
                'price' => 6500000000,
                'land_area' => 600,
                'building_area' => 350,
                'bedrooms' => 6,
                'bathrooms' => 5,
                'floors' => 2,
                'garage' => 4,
                'location' => 'Pantai Anyer KM 135',
                'city' => 'Serang',
                'province' => 'Banten',
                'latitude' => -6.0345,
                'longitude' => 105.8931,
                'facilities' => ['Private Beach', 'Pool', 'Gazebo', 'BBQ Area', 'Garden'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Apartemen Studio Kemang',
                'type' => 'apartment',
                'description' => 'Studio apartment fully furnished di kawasan Kemang yang happening.',
                'price' => 980000000,
                'building_area' => 32,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'floors' => 1,
                'garage' => 1,
                'location' => 'Kemang Village Residence',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'latitude' => -6.2615,
                'longitude' => 106.8172,
                'facilities' => ['Furnished', 'Mall Access', 'Pool', 'Gym', 'Cafe'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Rumah KPR Tanpa DP Bekasi',
                'type' => 'house',
                'description' => 'Program khusus rumah KPR tanpa down payment. Langsung huni, cicilan ringan.',
                'price' => 650000000,
                'land_area' => 90,
                'building_area' => 60,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'floors' => 1,
                'garage' => 1,
                'location' => 'Grand Galaxy City Bekasi',
                'city' => 'Bekasi',
                'province' => 'Jawa Barat',
                'latitude' => -6.2854,
                'longitude' => 107.0519,
                'facilities' => ['Club House', 'Security', 'Park', 'Commercial Area', 'School'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Rumah Minimalis Pamulang',
                'type' => 'house',
                'description' => 'Rumah minimalis modern dengan budget terjangkau. Cocok untuk first home buyer.',
                'price' => 850000000,
                'land_area' => 105,
                'building_area' => 70,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'floors' => 1,
                'garage' => 1,
                'location' => 'Pamulang Permai Estate',
                'city' => 'Tangerang Selatan',
                'province' => 'Banten',
                'latitude' => -6.3429,
                'longitude' => 106.7383,
                'facilities' => ['Security', 'Park', 'Masjid', 'Sport Center', 'Market'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Ruko Strategis Kelapa Gading',
                'type' => 'house',
                'description' => 'Ruko hook 4 lantai di jalur protokol Kelapa Gading. High traffic area.',
                'price' => 8500000000,
                'land_area' => 120,
                'building_area' => 400,
                'bedrooms' => 0,
                'bathrooms' => 4,
                'floors' => 4,
                'garage' => 3,
                'location' => 'Jl. Boulevard Kelapa Gading',
                'city' => 'Jakarta Utara',
                'province' => 'DKI Jakarta',
                'latitude' => -6.1572,
                'longitude' => 106.9100,
                'facilities' => ['Hook Position', 'Wide Frontage', 'Parking', 'Near Mall', 'CCTV'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Townhouse PIK 2',
                'type' => 'house',
                'description' => 'Townhouse eksklusif di kawasan PIK 2. Modern design dengan fasilitas premium.',
                'price' => 7800000000,
                'land_area' => 180,
                'building_area' => 280,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'floors' => 3,
                'garage' => 2,
                'location' => 'Pantai Indah Kapuk 2',
                'city' => 'Jakarta Utara',
                'province' => 'DKI Jakarta',
                'latitude' => -6.1078,
                'longitude' => 106.7403,
                'facilities' => ['Private Pool', 'Rooftop', 'Security', 'Club House', 'Beach Access'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Rumah Cluster Bintaro Jaya',
                'type' => 'house',
                'description' => 'Rumah cluster dengan konsep green living. Banyak ruang terbuka hijau.',
                'price' => 1750000000,
                'land_area' => 135,
                'building_area' => 100,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'floors' => 2,
                'garage' => 1,
                'location' => 'Bintaro Jaya Sektor 9',
                'city' => 'Tangerang Selatan',
                'province' => 'Banten',
                'latitude' => -6.2763,
                'longitude' => 106.7519,
                'facilities' => ['Park', 'Jogging Track', 'Security', 'Playground', 'Club House'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Apartemen Kuningan City',
                'type' => 'apartment',
                'description' => 'Apartemen premium di pusat bisnis Kuningan. Akses mudah ke SCBD dan Sudirman.',
                'price' => 4500000000,
                'building_area' => 120,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'floors' => 1,
                'garage' => 2,
                'location' => 'Denpasar Residence Kuningan',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'latitude' => -6.2259,
                'longitude' => 106.8302,
                'facilities' => ['Mall Access', 'Gym', 'Pool', 'City View', 'Concierge'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Villa Bogor Highland',
                'type' => 'house',
                'description' => 'Villa di kawasan pegunungan Bogor. Udara sejuk dan pemandangan indah.',
                'price' => 3200000000,
                'land_area' => 400,
                'building_area' => 220,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'floors' => 2,
                'garage' => 2,
                'location' => 'Highland Park Resort Bogor',
                'city' => 'Bogor',
                'province' => 'Jawa Barat',
                'latitude' => -6.6983,
                'longitude' => 106.9536,
                'facilities' => ['Mountain View', 'Garden', 'BBQ Area', 'Security', 'Cool Climate'],
                'is_featured' => false,
                'is_active' => true,
            ],
        ];

        foreach ($products as $productData) {
            $product = Product::create($productData);

            // Add sample images
            $imageUrls = [
                'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
                'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
                'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
            ];

            foreach ($imageUrls as $index => $url) {
                ProductImage::create([
                    'product_uid' => $product->uid,
                    'image_path' => $url,
                    'order' => $index + 1,
                    'is_primary' => $index === 0,
                ]);
            }
        }
    }
}
